# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: University of Washington eScience Institute
author: eScience Institute, University of Washington
logo: logo.png

# No notebooks in this book
#execute:
#  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/uwhackweek/hackweeks-as-a-service  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Bibliography
bibtex_bibfiles:
  - references.bib

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-RP8169MN6Q
